### ISSUE TITLE
[Tool error] Indentation problem in modules/linkedinphisher.py

### ISSUE THREAD

**Issue by s7x** [Greenwolf/social_attacker#1]
Hi there!

There is an error when running the script.

```
Traceback (most recent call last):
  File "social_attacker.py", line 2, in <module>
    from modules import linkedinphisher
  File "/usr/share/social-attacker/modules/linkedinphisher.py", line 225
    if (new_height == last_height or breakoutcount > 100):
                                                         ^
TabError: inconsistent use of tabs and spaces in indentation
```

In the file **modules/linkedinphisher.py** line **255**.

Cheers & thanks!

**Comment by phydroxide** [comment]
Same

Traceback (most recent call last):
  File "....social_attacker/social_attacker.py", line 2, in <module>
    from modules import linkedinphisher
  File "...social_attacker/modules/linkedinphisher.py", line 225
    if (new_height == last_height or breakoutcount > 100):
TabError: inconsistent use of tabs and spaces in indentation
